swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /books:
    get:
      operationId: readAllBook
      tags:
        - books
      x-swagger-router-controller: controllers.book_controller
      responses:
        200:
          description: Successful read books list
          schema:
            type: array
            items:
              properties:
                book_id:
                  type: string
                  description: ID of the book
                book_title:
                  type: string
                  description: book_title
                author_name:
                  type: string
                  description: Name of the book's author
            
    post:
      operationId: createBook
      tags:
        - books
      x-swagger-router-controller: controllers.book_controller
      parameters:
        - name: book
          in: body
          description: data for book creation
          required: True
          schema:
            type: object
            properties:
              title:
                type: string
                description: Book title
              author:
                type: string
                description: Author's name
      responses:
        201:
          description: Successful create book operation
          schema:
            properties:
              id:
                type: string
                description: Id of the book
              title:
                type: string
                description: Book title
              author:
                type: string
                description: Author's name

    
  /book/{book_id}:
    delete:
      operationId: deleteBook
      tags:
        - books
      summary: Deletes a book given its id
      x-swagger-router-controller: controllers.book_controller
      parameters:
        - name: book_id
          in: path
          type: string
          required: True
          description: Id of the resource to delete
      responses:
        200:
          description: Successfully deleted a book from book list

    get:
      operationId: readOneBook
      tags:
        - books
      summary: Read one book by id
      x-swagger-router-controller: controllers.book_controller
      parameters:
        - name: book_id
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully read book from book list 
          schema:
            properties:
              id:
                type: string
                description: ID of the book
              title:
                type: string
                description: Book's title
              author:
                type: string
                description: Book's author

    put:
      operationId: updateBook
      tags:
        - books
      summary: Update an existing book
      x-swagger-router-controller: controllers.book_controller
      parameters:
        - name: book_id
          in: path
          description: ID of the book to update
          type: string
          required: True
        - name: book
          in: body
          schema: 
            type: object
            properties: 
              title:
                type: string
              author:
                type: string
      responses:
        200:
          description: Successfully updated book
          schema:
            properties:
              id:
                type: string
                description: ID of inter-site resource
              title:
                type: string
                description: Book's title
              author:
                type: string
                description: Author's title
